### ISSUE TITLE
Can´t install in Foundry v12.328

### ISSUE THREAD

**Issue by Q-efx** [Genii-Locorum/outgunned#4]
I get this error message:

setup.js:2113 
Error: The downloaded package outgunned did not contain the expected system.json manifest file.
    at #s (/home/foundry/resour…nstaller.mjs:1:1059)
    at async PackageInstaller.install (/home/foundry/resour…installer.mjs:1:446)
    at async #s (/home/foundry/resour…/package.mjs:1:8994)
    at async System.install (/home/foundry/resour…/package.mjs:1:7830)
    at async System.install (/home/foundry/resour…s/system.mjs:1:2817)
    at async /home/foundry/resour…es/views.mjs:1:3321
setup.js:8566 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'split')
    at Setup.installPackage (setup.js:8566:44)
    at async #onClickPackageInstall (setup.js:7704:7)

**Comment by Genii-Locorum** [comment]
Thanks for calling this out.  I've released 2.0.3 which should fix the problem.

Apologies for the inconvenience.

If you can confirm it now loads scucesfully I will close the issue.

**Comment by Q-efx** [comment]
> Thanks for calling this out. I've released 2.0.3 which should fix the problem.
> 
> Apologies for the inconvenience.
> 
> If you can confirm it now loads successfully I will close the issue.

Hi,

Thanks, it's working now.
